name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Step 1: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Step 2: Install Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10

    # Step 3: Initialize Conda and create environment
    - name: Create and activate Conda environment
      run: |
        conda create --name ai_bobo_env python=3.10 -y
        conda init bash  # Initialize conda for the current shell
        source ~/.bashrc  # Reload shell to apply conda init changes
        conda activate ai_bobo_env  # Now activate the created environment
    
    # Step 4: Upgrade setuptools and wheel
    - name: Upgrade setuptools and wheel
      run: |
        pip install --upgrade setuptools wheel
      shell: bash -l {0}  # Make sure the shell is a login shell

    # Step 5: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      shell: bash -l {0}  # Ensure it runs inside the activated environment

    # Step 6: Lint the code with flake8 (optional)
    - name: Run lint with flake8
      run: flake8 .
      shell: bash -l {0}

    # Step 7: Run tests (optional)
    - name: Run tests
      run: pytest
      shell: bash -l {0}
